Remove ProjectIntegrityTest and corresponding dependencies
Some (transitive) dependencies that are used for the
ProjectIntegrityTest cause test generation via EvoSuite to fail with:

Fatal crash on main EvoSuite process. Class  using seed 0. Configuration id : null
java.lang.IllegalArgumentException: Unsupported class file major version 65

To resolve this issue, this commit removes the test and corresponding
dependencies (we cannot generalize the ProjectIntegrityTest anyway).